INSERT INTO Users
	(First_name, Last_name, Email, Phone, Type, Password, Blocked) 
VALUES
	-- STAFF Users
	('John', 'Doe', 'johndoe@library.com', '8761234567', 'STAFF', 'e99a18c428cb38d5f260853678922e03', 0),
	('Mary', 'Smith', 'marysmith@library.com', '8762345678', 'STAFF', '5f4dcc3b5aa765d61d8327deb882cf99', 0),
	('David', 'Brown', 'davidbrown@library.com', '8763456789', 'STAFF', '25d55ad283aa400af464c76d713c07ad', 0),
	-- Regular Users
	('Alice', 'Johnson', 'alicejohnson@library.com', '8764567890', 'USER', '202cb962ac59075b964b07152d234b70', 0),
	('Robert', 'Williams', 'robertwilliams@library.com', '8765678901', 'USER', '098f6bcd4621d373cade4e832627b4f6', 0),
	('Sophia', 'Davis', 'sophiadavis@library.com', '8766789012', 'USER', '81dc9bdb52d04dc20036dbd8313ed055', 0),
	('James', 'Miller', 'jamesmiller@library.com', '8767890123', 'USER', 'c4ca4238a0b923820dcc509a6f75849b', 0),
	('Emily', 'Wilson', 'emilywilson@library.com', '8768901234', 'USER', 'eccbc87e4b5ce2fe28308fd9f2a7baf3', 0),
	('Michael', 'Moore', 'michaelmoore@library.com', '8769012345', 'USER', 'a87ff679a2f3e71d9181a67b7542122c', 0),
	('Jessica', 'Taylor', 'jessicataylor@library.com', '8769123456', 'USER', 'e4da3b7fbbce2345d7772b0674a318d5', 0),
	('Daniel', 'Anderson', 'danielanderson@library.com', '8769234567', 'USER', '1679091c5a880faf6fb5e6087eb1b2dc', 0),
	('Olivia', 'Thomas', 'oliviathomas@library.com', '8769345678', 'USER', '8f14e45fceea167a5a36dedd4bea2543', 0);
GO


INSERT INTO Books
	(Title, Description, Author, PublishedYear, Available) 
VALUES
	('The Catcher in the Rye', 'A novel about teenage alienation.', 'J.D. Salinger', 1951, 1),
	('To Kill a Mockingbird', 'A novel about racial injustice.', 'Harper Lee', 1960, 1),
	('1984', 'A dystopian novel on totalitarianism.', 'George Orwell', 1949, 1),
	('Pride and Prejudice', 'A classic romance novel.', 'Jane Austen', 1813, 1),
	('The Great Gatsby', 'A novel about the American Dream.', 'F. Scott Fitzgerald', 1925, 1),
	('Moby-Dick', 'A novel about the hunt for a great white whale.', 'Herman Melville', 1851, 1),
	('War and Peace', 'A historical novel set in the Napoleonic era.', 'Leo Tolstoy', 1869, 1),
	('The Odyssey', 'An epic Greek poem.', 'Homer', -800, 1),
	('Crime and Punishment', 'A psychological novel about morality.', 'Fyodor Dostoevsky', 1866, 1),
	('The Brothers Karamazov', 'A novel about faith and family conflicts.', 'Fyodor Dostoevsky', 1880, 1),
	('Brave New World', 'A dystopian novel on technology and control.', 'Aldous Huxley', 1932, 1),
	('The Lord of the Rings', 'A high-fantasy adventure.', 'J.R.R. Tolkien', 1954, 1),
	('The Hobbit', 'A prelude to The Lord of the Rings.', 'J.R.R. Tolkien', 1937, 1),
	('Frankenstein', 'A gothic novel about scientific ambition.', 'Mary Shelley', 1818, 1),
	('Dracula', 'A classic vampire novel.', 'Bram Stoker', 1897, 1),
	('The Picture of Dorian Gray', 'A novel about vanity and corruption.', 'Oscar Wilde', 1890, 1),
	('Les Misérables', 'A novel about redemption and revolution.', 'Victor Hugo', 1862, 1),
	('Jane Eyre', 'A gothic romance novel.', 'Charlotte Brontë', 1847, 1),
	('Wuthering Heights', 'A story of love and revenge.', 'Emily Brontë', 1847, 1),
	('The Count of Monte Cristo', 'A novel about betrayal and revenge.', 'Alexandre Dumas', 1844, 1),
	('Fahrenheit 451', 'A dystopian novel about book burning.', 'Ray Bradbury', 1953, 1),
	('The Road', 'A post-apocalyptic survival story.', 'Cormac McCarthy', 2006, 1),
	('Dune', 'A sci-fi novel about politics and ecology.', 'Frank Herbert', 1965, 1),
	('The Alchemist', 'A novel about destiny and dreams.', 'Paulo Coelho', 1988, 1),
	('The Kite Runner', 'A novel about friendship and redemption.', 'Khaled Hosseini', 2003, 1),
	('A Game of Thrones', 'A medieval fantasy epic.', 'George R.R. Martin', 1996, 1),
	('A Clash of Kings', 'The second book in A Song of Ice and Fire.', 'George R.R. Martin', 1998, 1),
	('A Storm of Swords', 'The third book in A Song of Ice and Fire.', 'George R.R. Martin', 2000, 1),
	('A Feast for Crows', 'The fourth book in A Song of Ice and Fire.', 'George R.R. Martin', 2005, 1),
	('A Dance with Dragons', 'The fifth book in A Song of Ice and Fire.', 'George R.R. Martin', 2011, 1),
	('The Shining', 'A horror novel set in a haunted hotel.', 'Stephen King', 1977, 1),
	('It', 'A horror novel about an evil entity.', 'Stephen King', 1986, 1),
	('Misery', 'A psychological thriller.', 'Stephen King', 1987, 1),
	('Pet Sematary', 'A horror novel about resurrection.', 'Stephen King', 1983, 1),
	('The Stand', 'A post-apocalyptic novel.', 'Stephen King', 1978, 1),
	('11/22/63', 'A time-travel novel to prevent JFK’s assassination.', 'Stephen King', 2011, 1),
	('The Girl with the Dragon Tattoo', 'A mystery thriller.', 'Stieg Larsson', 2005, 1),
	('The Girl Who Played with Fire', 'The second book in the Millennium series.', 'Stieg Larsson', 2006, 1),
	('The Girl Who Kicked the Hornet’s Nest', 'The third book in the Millennium series.', 'Stieg Larsson', 2007, 1),
	('Angels & Demons', 'A thriller about secret societies.', 'Dan Brown', 2000, 1),
	('The Da Vinci Code', 'A conspiracy thriller.', 'Dan Brown', 2003, 1),
	('Inferno', 'A thriller about Dante’s Inferno.', 'Dan Brown', 2013, 1),
	('Digital Fortress', 'A novel about cryptography.', 'Dan Brown', 1998, 1),
	('The Lost Symbol', 'A mystery novel about Freemasonry.', 'Dan Brown', 2009, 1),
	('Sapiens', 'A non-fiction book on human history.', 'Yuval Noah Harari', 2011, 1),
	('Homo Deus', 'A book about the future of humanity.', 'Yuval Noah Harari', 2015, 1),
	('Atomic Habits', 'A book on self-improvement.', 'James Clear', 2018, 1),
	('The Subtle Art of Not Giving a F*ck', 'A self-help book on priorities.', 'Mark Manson', 2016, 1),
	('Thinking, Fast and Slow', 'A book about decision-making.', 'Daniel Kahneman', 2011, 1),
	('The Silent Patient', 'A psychological thriller about a woman who stops speaking after a crime.', 'Alex Michaelides', 2019, 1),
	('The Midnight Library', 'A novel about infinite possibilities.', 'Matt Haig', 2020, 1),
	('Circe', 'A retelling of the mythological tale of Circe.', 'Madeline Miller', 2018, 1),
	('The House in the Cerulean Sea', 'A fantasy novel about belonging and love.', 'TJ Klune', 2020, 1),
	('The Night Circus', 'A novel about a mysterious magical competition.', 'Erin Morgenstern', 2011, 1),
	('Project Hail Mary', 'A sci-fi novel about a lone astronaut.', 'Andy Weir', 2021, 1),
	('The Martian', 'A novel about survival on Mars.', 'Andy Weir', 2014, 1),
	('Artemis', 'A sci-fi thriller set on the Moon.', 'Andy Weir', 2017, 1),
	('Cloud Atlas', 'A novel spanning different time periods.', 'David Mitchell', 2004, 1),
	('The Bone Clocks', 'A fantasy novel about time and immortality.', 'David Mitchell', 2014, 1),
	('Piranesi', 'A mysterious novel set in an infinite labyrinth.', 'Susanna Clarke', 2020, 1),
	('Jonathan Strange & Mr Norrell', 'A novel about magic in 19th-century England.', 'Susanna Clarke', 2004, 1),
	('Shantaram', 'A novel about a fugitive in India.', 'Gregory David Roberts', 2003, 1),
	('A Man Called Ove', 'A heartwarming story about an old man rediscovering life.', 'Fredrik Backman', 2012, 1),
	('Beartown', 'A novel about a small town and its hockey team.', 'Fredrik Backman', 2016, 1),
	('Where the Crawdads Sing', 'A coming-of-age mystery novel.', 'Delia Owens', 2018, 1),
	('The Tattooist of Auschwitz', 'A novel based on a true Holocaust story.', 'Heather Morris', 2018, 1),
	('Cilka’s Journey', 'A sequel to The Tattooist of Auschwitz.', 'Heather Morris', 2019, 1),
	('Before We Were Strangers', 'A novel about lost love and second chances.', 'Renée Carlino', 2015, 1),
	('Eleanor Oliphant Is Completely Fine', 'A novel about loneliness and friendship.', 'Gail Honeyman', 2017, 1),
	('Verity', 'A psychological thriller with dark secrets.', 'Colleen Hoover', 2018, 1),
	('It Ends With Us', 'A novel about love and resilience.', 'Colleen Hoover', 2016, 1),
	('Reminders of Him', 'A novel about redemption and second chances.', 'Colleen Hoover', 2022, 1),
	('The Seven Husbands of Evelyn Hugo', 'A historical fiction about fame and love.', 'Taylor Jenkins Reid', 2017, 1),
	('Daisy Jones & The Six', 'A novel about a fictional rock band.', 'Taylor Jenkins Reid', 2019, 1),
	('Malibu Rising', 'A novel about a famous family and their secrets.', 'Taylor Jenkins Reid', 2021, 1),
	('Carrie Soto Is Back', 'A novel about a tennis star’s comeback.', 'Taylor Jenkins Reid', 2022, 1),
	('The 5 AM Club', 'A self-help book on morning routines.', 'Robin Sharma', 2018, 1),
	('The Mountain Is You', 'A self-improvement book on overcoming obstacles.', 'Brianna Wiest', 2020, 1),
	('Can’t Hurt Me', 'A memoir about mental toughness.', 'David Goggins', 2018, 1),
	('The Power of Now', 'A book on mindfulness and living in the present.', 'Eckhart Tolle', 1997, 1),
	('Man’s Search for Meaning', 'A book on finding purpose in suffering.', 'Viktor E. Frankl', 1946, 1),
	('The Four Agreements', 'A book about personal freedom.', 'Don Miguel Ruiz', 1997, 1),
	('How to Win Friends and Influence People', 'A book on communication and leadership.', 'Dale Carnegie', 1936, 1),
	('Think and Grow Rich', 'A classic self-help book on wealth and success.', 'Napoleon Hill', 1937, 1),
	('The Psychology of Money', 'A book on financial habits and mindset.', 'Morgan Housel', 2020, 1),
	('The 48 Laws of Power', 'A book on power dynamics.', 'Robert Greene', 1998, 1),
	('The Art of War', 'A classic book on strategy.', 'Sun Tzu', -500, 1),
	('Meditations', 'A book of philosophical reflections.', 'Marcus Aurelius', 180, 1),
	('Atomic Habits', 'A book on habit-building.', 'James Clear', 2018, 1),
	('Deep Work', 'A book on focus and productivity.', 'Cal Newport', 2016, 1),
	('Essentialism', 'A book about focusing on what truly matters.', 'Greg McKeown', 2014, 1),
	('The Lean Startup', 'A book on modern entrepreneurship.', 'Eric Ries', 2011, 1),
	('Hooked', 'A book on how to build habit-forming products.', 'Nir Eyal', 2014, 1),
	('The Innovator’s Dilemma', 'A book about disruptive innovation.', 'Clayton M. Christensen', 1997, 1),
	('Zero to One', 'A book on startups and innovation.', 'Peter Thiel', 2014, 1),
	('Good to Great', 'A book on why some companies succeed.', 'Jim Collins', 2001, 1),
	('The Hard Thing About Hard Things', 'A book about managing a startup.', 'Ben Horowitz', 2014, 1),
	('Shoe Dog', 'A memoir by the founder of Nike.', 'Phil Knight', 2016, 1),
	('Elon Musk: Tesla, SpaceX, and the Quest for a Fantastic Future', 'A biography of Elon Musk.', 'Ashlee Vance', 2015, 1),
	('Steve Jobs', 'A biography of Steve Jobs.', 'Walter Isaacson', 2011, 1),
	('Leonardo da Vinci', 'A biography of the Renaissance genius.', 'Walter Isaacson', 2017, 1),
	('Einstein: His Life and Universe', 'A biography of Albert Einstein.', 'Walter Isaacson', 2007, 1),
	('The Wright Brothers', 'A biography of aviation pioneers.', 'David McCullough', 2015, 1);
GO
